project:
  type: website
  output-dir: docs
  
format: 
  html:
    theme:
      light: yeti
      dark: darkly
    toc: true
    toc-location: left
    toc-floating: true
    toc-depth: 3
    page-layout: article